workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build Flutter iOS app for simulator
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
