workflows:
  ios-build:
    name: iOS Build Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build for iOS Simulator
        script: |
          xcodebuild build \
            -workspace "YourApp.xcworkspace" \
            -scheme "YourAppScheme" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=18.2' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
